config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/new'

  get 'welcome/index'

  resources :posts do
    resources :comments
end

resources :users do
    resources :posts
end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true,
                    length: { minimum: 5}
    has_many :comments, dependent: :destroy    
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @post = Post.find_by(params[:id])
    @post_id = @post.id
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params) 
    if @comment.save
      redirect_to post_path(@post)
    else 
      render new_post_path
    end
   
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
      @post = Post.find{params[:id]}
      @comments = @post.comments.find{params[:id]}
      @comments.destroy
      redirect_to post_path(@post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :post_id)
    end
    def post_params
        params.require(:post).permit(:id, :title, :text)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:index, :show]

    def index
        @posts = Post.all
    end
    def show
        @post = Post.find(params[:id])
        
        @comments = @post.comments.all
        @comment = @post.comments.build
    end

    def new
        @post = current_user.posts.build
    end
    
    def edit
        @post = Post.find(params[:id])
    end

    def create
        @post = current_user.posts.build(params.require(:post).permit(:title, :text))

        if @post.save
        redirect_to @post
        else
            render 'new'
    end
end


    
    
    
    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to posts_path
    end
    
    private
    def require_login
        unless logged_in?
            flash[:error] = "Hey! You Have to Sign In!"
            redirect_to new_login_url
        end
    end
    def post_params
        params.require(:post).permit(:title, :text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Really?!?' } %>
</p>

app/views/comments/_form.html.erb
<div class='comment-form'>
<%= form_for [@post, @post.comments.build] do |c| %>
  <%= c.hidden_field :post_id, :value=> @post_id %>
  <%= c.text_field :user_name %>
  <%= c.text_field :body %>
  <%= c.submit %>
<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bumblr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <%= link_to "Sign Up", new_user_registration_path %>
        <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Out",  destroy_user_session_path, method: :delete %>
      <%= yield %>
  
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>

    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
            </h2>
            <ul>
                <% @post.errors.full_messages.each do |m| %>
                    <li>
                        <%= m %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>

            <p>
                <%= form.label :title %>
                    <br>
                    <%= form.text_area :text %>
            </p>

            <p>
                <%= form.submit %>
            </p>
            <% end %>

app/views/posts/edit.html.erb
<h1>Edit</h1>


<%= form_with(model: @post) do |form| %>

    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
            </h2>
            <ul>
                <% @post.errors.full_messages.each do |m|  %>
                    <li>
                        <%= m %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>

            <p>
                <%= form.label :title %>
                    <br>
                    <%= form.text_area :text %>
            </p>

            <p>
                <%= form.submit %>
            </p>

            <% end %>
            
                <%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= link_to 'New Post', new_post_path %>
<br>
    <table>
        <tr>
            <th>Title</th>
            <br>
            <th>Text</th>
            <th>User</th>
            <th colspan="2"></th>
        </tr>

        <% @posts.each do |post|  %>
            <tr>
                <td>
                    <%= post.title %>
                </td>
                <td>
                    <%= post.text %>
                </td>
                <td>
                    <%= post.user.email %>
                </td>
                <td>
                        <%= link_to 'Show', post_path(post) %>
                </td>
                <% if post.user == current_user %>
                <td>
                    <%= link_to 'Edit', edit_post_path(post) %>
                </td>
                <td>
                <%= link_to 'Destroy', posts_path, 
                    method: :delete,
                    data: { confirm: 'Really? You want to delete this?'}
                %>
                </td>
                <% end %>
            </tr>
            <% end %>

    </table>

app/views/posts/new.html.erb
<h1>Create New Post</h1>


<%= form_with scope: :post, url: posts_path, local: true do |form| %>
    <% if @post.errors.any?  %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
            </h2>
            <ul>
                <% @post.errors.full_messages.each do |m|  %>
                    <li>
                        <%= m %>
                    </li>
                    <% end  %>
            </ul>
        </div>
        <% end %>

            <p>
                <%= form.label :title %>
                    <br>
                    <%= form.text_field :title %>
            </p>

            <p>
                <%= form.label :text %>
                    <br>
                    <%= form.text_area :text %>
            </p>

            <p>
                <%= form.submit %>
            </p>

            <% end  %>

                <%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @post.text %>
</p>

<h2>Comments</h2>
<% @comments.each do |c| %>
<div>
<strong><%= c.user_name %></strong>
<br>
<p><%= c.body %></p>
<p><%= link_to 'Delete', post_comment_path(c), method: :delete, date: { confirm: 'REALLY?!?!' } %></p>
</div>
<% end %>



<%#= render partial: 'comments/form', locals: { comment: @comment }%>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>bumblr</h1>

<%= link_to 'To My Blog', controller: 'posts' %>